---
- name: Instalar y configurar Minikube localmente
  hosts: localhost
  connection: local

  vars_files:          
    - "{{ playbook_dir }}/vault.yml"

  vars:
    ansible_become_password: "{{ vault_sudo_password }}"

  tasks:
    - name: Instalar dependencias necesarias
      become: true     
      #ansible.builtin.apt
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - apt-transport-https

    - name: Descargar Minikube
      become: true     
      get_url:
        url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        dest: /usr/local/bin/minikube
        mode: '0755'

    - name: Descargar kubectl (Versión estable)
      become: true     
      get_url:
        url: https://dl.k8s.io/release/v1.31.0/bin/linux/amd64/kubectl
        dest: /usr/local/bin/kubectl
        mode: '0755'
    
    - name: Verificar el estado actual de Minikube
      command: minikube status
      register: minikube_status
      failed_when: false
      changed_when: false

    - name: Iniciar Minikube si está detenido o no existe
      command: minikube start --driver=docker
      when: "'Running' not in minikube_status.stdout"

#    - name: Iniciar Minikube
#      command: minikube start --driver=docker
