---
- name: Instalar y configurar Minikube localmente
  hosts: localhost
  connection: local

  vars_files:          
    - "{{ playbook_dir }}/vault.yml"

  vars:
    ansible_become_password: "{{ vault_sudo_password }}"

  tasks:
    - name: Instalar dependencias necesarias
      become: true     
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - apt-transport-https
        - virtualbox

    - name: Descargar Minikube
      become: true     
      get_url:
        url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        dest: /usr/local/bin/minikube
        mode: '0755'

    - name: Descargar kubectl (Versión estable)
      become: true     
      get_url:
        url: https://dl.k8s.io/release/v1.31.0/bin/linux/amd64/kubectl
        dest: /usr/local/bin/kubectl
        mode: '0755'

    - name: Iniciar Minikube
      command: minikube start --driver=docker
