- name: Instalar y configurar Minikube localmente
  hosts: localhost
  become: yes
  tasks:
    - name: Instalar dependencias necesarias
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - apt-transport-https
        - virtualbox

    - name: Descargar Minikube
      get_url:
        url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        dest: /usr/local/bin/minikube
        mode: '0755'

    - name: Descargar kubectl
      get_url:
        url: https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
        dest: /usr/local/bin/kubectl
        mode: '0755'

    - name: Iniciar Minikube
      command: minikube start --driver=virtualbox
