name: Test Minikube Setup

on:
  push:
    branches:
      - main

jobs:
  test-minikube:
    runs-on: self-hosted
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Minikube setup playbook
        run: ansible-playbook ansible/setup-minikube-playbook.yml
